# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Rcpp_encode_maximal_column_of_u <- function(u, egs, efficient = TRUE) {
    .Call('_mspbwt_Rcpp_encode_maximal_column_of_u', PACKAGE = 'mspbwt', u, egs, efficient)
}

#' @export
Rcpp_decode_maximal_value_of_u <- function(out_mat, out_vec, v, egs, do_checks = FALSE) {
    .Call('_mspbwt_Rcpp_decode_maximal_value_of_u', PACKAGE = 'mspbwt', out_mat, out_vec, v, egs, do_checks)
}

#' @export
BuildIndices_Algorithm5_Rcpp <- function(X) {
    .Call('_mspbwt_BuildIndices_Algorithm5_Rcpp', PACKAGE = 'mspbwt', X)
}

#' @export
MatchZ_Algorithm5_Rcpp <- function(X, a, u, v, c, d, Z, verbose = FALSE, do_checks = FALSE, start_rows = 100L) {
    .Call('_mspbwt_MatchZ_Algorithm5_Rcpp', PACKAGE = 'mspbwt', X, a, u, v, c, d, Z, verbose, do_checks, start_rows)
}

